apiVersion: v1
kind: Service
metadata:
  name: tanzu-sample-service2
spec:
  type: LoadBalancer
  selector:
    app: tanzu-sample-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
